import {uid,durationLabel,dayKey,startOfDay,sleepMinutes,periodStats,wakeWindows,prediction,correctedAgeMonths} from './core.js';

const DB='sonya-sleep', STORE='state';
const defaultState={children:[],events:[],settings:{theme:'light',notifications:false,vibration:true},demo:false};
let state=structuredClone(defaultState), view='today', historyMode='list', period='week', selectedDate=new Date(), ticker;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function dbOpen(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function load(){const db=await dbOpen();return new Promise(resolve=>{const r=db.transaction(STORE).objectStore(STORE).get('app');r.onsuccess=()=>resolve(r.result||structuredClone(defaultState));r.onerror=()=>resolve(structuredClone(defaultState))})}
async function save(){const db=await dbOpen(); await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(state,'app');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
const child=()=>state.children.find(c=>c.id===state.settings.activeChild)||state.children[0];
const events=()=>state.events.filter(e=>e.childId===child()?.id).sort((a,b)=>new Date(b.start)-new Date(a.start));
const active=()=>events().find(e=>!e.end);
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function vib(){if(state.settings.vibration&&navigator.vibrate)navigator.vibrate(35)}
function fmtTime(d){return new Date(d).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}
function fmtDate(d){return new Date(d).toLocaleDateString('ru-RU',{day:'numeric',month:'long'})}
function localInput(d){const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,16)}
function ageLabel(c){const m=Math.floor(correctedAgeMonths(c));return m<1?'меньше месяца':m<24?`${m} мес.`:`${Math.floor(m/12)} г. ${m%12} мес.`}

function layout(content){const c=child();return `<main class="shell" data-view="${view}"><header class="topbar"><div class="brand"><span class="brand-mark">☾</span>Соня</div><button class="child-switch" data-action="children"><span class="avatar">${c?.photo?`<img class="avatar" src="${c.photo}" alt="">`:'🧸'}</span>${esc(c?.name)}⌄</button></header>${content}</main><nav class="nav" aria-label="Основная навигация">${[['today','⌂','Сегодня'],['history','◷','История'],['stats','▥','Статистика'],['settings','⚙','Настройки']].map(([id,ic,t])=>`<button data-view="${id}" class="${view===id?'active':''}"><b>${ic}</b>${t}</button>`).join('')}</nav>${view!=='settings'?'<button class="fab" data-action="add" aria-label="Добавить сон">+</button>':''}`}
function heading(kicker,title,sub=''){return `<div class="page-head"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1>${sub?`<div class="muted">${sub}</div>`:''}</div></div>`}
function todayRange(offset=0){const a=startOfDay(new Date());a.setDate(a.getDate()+offset);const b=new Date(a);b.setDate(b.getDate()+1);return[a,b]}
function timeline(es,date=new Date()){const k=dayKey(date), d0=startOfDay(date), d1=new Date(d0);d1.setDate(d1.getDate()+1);const blocks=es.filter(e=>new Date(e.start)<d1&&new Date(e.end||Date.now())>d0).map(e=>{const st=Math.max(new Date(e.start),d0),en=Math.min(new Date(e.end||Date.now()),d1);return `<button title="${fmtTime(st)}–${fmtTime(en)}" data-edit="${e.id}" class="sleep-block ${e.sleepType}" style="left:${(st-d0)/864000}%;width:${Math.max(.5,(en-st)/864000)}%"></button>`}).join('');return `<div class="timeline">${blocks}</div><div class="time-axis"><span>00</span><span>06</span><span>12</span><span>18</span><span>24</span></div>`}

function todayView(){const [a,b]=todayRange(), s=periodStats(events(),a,b), act=active(), ended=events().filter(e=>e.end), last=ended[0], awake=last?Math.max(0,Math.round((Date.now()-new Date(last.end))/60000)):0, pred=prediction(child(),events());return layout(`${heading('Спокойный ритм',`Добрый день, ${esc(child().name)}`,ageLabel(child()))}<div class="grid"><section class="card hero"><div class="status"><i class="dot ${act?'sleeping':''}"></i>${act?'Сейчас спит':'Сейчас бодрствует'}</div><div class="timer">${act?durationLabel(sleepMinutes(act)):last?durationLabel(awake):'Начнём?'}</div><div class="muted">${act?`с ${fmtTime(act.start)}`:last?`после пробуждения в ${fmtTime(last.end)}`:'Добавьте первую запись сна'}</div><button class="primary big" data-action="toggle">${act?'Проснулся':'Уснул'}</button></section><aside class="quick"><div class="metric"><span>Всего сегодня</span><strong>${durationLabel(s.total)}</strong></div><div class="metric"><span>Дневной сон</span><strong>${durationLabel(s.day)}</strong></div><div class="metric"><span>Ночной сон</span><strong>${durationLabel(s.night)}</strong></div><div class="metric"><span>Снов сегодня</span><strong>${s.count}</strong></div></aside><section class="card wide"><div class="section-title"><h2>Следующий сон</h2><span class="eyebrow">${pred?.confidence||'после пробуждения'}</span></div><div style="font-size:28px;font-weight:800">${pred?.label||'Малыш сейчас отдыхает'}</div><p class="muted">${pred?.target?'Ориентир рассчитан с учётом возраста и последних окон бодрствования.':'Прогноз появится после завершения сна.'}</p><p class="disclaimer">Ориентир носит информационный характер, не является медицинской рекомендацией. Учитывайте состояние ребёнка и рекомендации педиатра.</p></section><section class="card wide"><div class="section-title"><h2>Ритм дня</h2><button class="ghost" data-view="history">Вся история</button></div>${timeline(events(),new Date())}</section></div>`)}
function entryList(es){return es.length?`<div class="entries">${es.map(e=>`<button class="entry" data-edit="${e.id}"><span class="entry-icon">${e.sleepType==='night'?'☾':'☁'}</span><span class="entry-main"><strong>${fmtTime(e.start)}–${e.end?fmtTime(e.end):'сейчас'}</strong><span>${e.sleepType==='night'?'Ночной':'Дневной'} сон · ${durationLabel(sleepMinutes(e))}${e.location?` · ${esc(e.location)}`:''}</span></span><b>›</b></button>`).join('')}</div>`:'<div class="empty"><div class="moon">☾</div><p>В этот день записей пока нет</p></div>'}
function calendar(){const base=new Date(selectedDate.getFullYear(),selectedDate.getMonth(),1), first=(base.getDay()+6)%7, days=new Date(base.getFullYear(),base.getMonth()+1,0).getDate();let out=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=>`<small style="text-align:center">${x}</small>`).join('');out+='<span></span>'.repeat(first);for(let i=1;i<=days;i++){const d=new Date(base.getFullYear(),base.getMonth(),i),[a,b]=[startOfDay(d),new Date(d.getFullYear(),d.getMonth(),d.getDate()+1)],s=periodStats(events(),a,b);out+=`<button class="calday ${s.total?'has':''} ${dayKey(d)===dayKey(new Date())?'today':''}" data-day="${d.toISOString()}"><b>${i}</b>${s.total?`<small style="display:block">${Math.round(s.total/60)}ч</small>`:''}</button>`}return `<div class="calendar">${out}</div>`}
function historyView(){const dayEvents=events().filter(e=>dayKey(e.start)===dayKey(selectedDate)||dayKey(e.end||e.start)===dayKey(selectedDate));return layout(`${heading('Все записи','История сна',fmtDate(selectedDate))}<div class="tabs"><button data-hmode="list" class="${historyMode==='list'?'active':''}">Список</button><button data-hmode="line" class="${historyMode==='line'?'active':''}">Шкала суток</button><button data-hmode="calendar" class="${historyMode==='calendar'?'active':''}">Календарь</button></div><section class="card">${historyMode==='list'?entryList(dayEvents):historyMode==='line'?`${timeline(dayEvents,selectedDate)}<div style="margin-top:24px">${entryList(dayEvents)}</div>`:calendar()}</section>`)}
function periodRange(){const now=new Date();if(period==='today')return todayRange();if(period==='yesterday')return todayRange(-1);let a=startOfDay(now),b=new Date(a);b.setDate(b.getDate()+1);if(period==='week')a.setDate(a.getDate()-6);else if(period==='month')a.setDate(a.getDate()-29);return[a,b]}
function statsView(){const[a,b]=periodRange(),s=periodStats(events(),a,b),windows=wakeWindows(events());const days=Math.max(1,Math.round((b-a)/86400000)), bars=[];for(let i=0;i<days;i++){const d=new Date(a);d.setDate(d.getDate()+i);const e=new Date(d);e.setDate(e.getDate()+1);bars.push({d,total:periodStats(events(),d,e).total})}const max=Math.max(...bars.map(x=>x.total),1);return layout(`${heading('Аналитика','Статистика','Нейтральные данные без оценок')}<div class="periods">${[['today','Сегодня'],['yesterday','Вчера'],['week','7 дней'],['month','30 дней']].map(([k,l])=>`<button data-period="${k}" class="${period===k?'active':''}">${l}</button>`).join('')}</div><div class="grid"><section class="card"><div class="quick"><div class="metric"><span>Всего сна</span><strong>${durationLabel(s.total)}</strong></div><div class="metric"><span>Средний сон</span><strong>${durationLabel(s.average)}</strong></div><div class="metric"><span>День / ночь</span><strong>${Math.round(s.day/60)} / ${Math.round(s.night/60)} ч</strong></div><div class="metric"><span>Среднее бодрствование</span><strong>${durationLabel(windows.length?Math.round(windows.reduce((a,x)=>a+x,0)/windows.length):0)}</strong></div></div></section><section class="card"><h2 style="margin-top:0">Ночные пробуждения</h2><div class="timer" style="font-size:42px">${s.awakenings}</div><p class="muted">за выбранный период</p></section><section class="card wide"><div class="section-title"><h2>Сон по дням</h2><span class="muted">часов</span></div><div class="chart">${bars.map((x,i)=>`<div class="bar-wrap"><div class="bar" title="${durationLabel(x.total)}" style="height:${Math.max(3,x.total/max*145)}px"></div><small>${days>10?(i%5===0?x.d.getDate():''):x.d.toLocaleDateString('ru-RU',{weekday:'short'})}</small></div>`).join('')}</div></section></div>`)}
function settingsView(){return layout(`${heading('Ваше пространство','Настройки','Данные остаются только на этом устройстве')}<div class="grid"><section class="card settings"><h2>Внешний вид</h2><div class="setting-row"><span>Ночная тема</span><button class="switch ${state.settings.theme==='dark'?'on':''}" data-action="theme" aria-label="Переключить тему"></button></div><div class="setting-row"><span>Вибрация</span><button class="switch ${state.settings.vibration?'on':''}" data-action="vibration"></button></div><div class="setting-row"><span>Напоминания</span><button class="switch ${state.settings.notifications?'on':''}" data-action="notifications"></button></div></section><section class="card settings"><h2>Дети</h2>${state.children.map(c=>`<div class="setting-row"><span><b>${esc(c.name)}</b><br><small class="muted">${ageLabel(c)}</small></span><button class="ghost" data-edit-child="${c.id}">Изменить</button></div>`).join('')}<button class="secondary" data-action="new-child">+ Добавить ребёнка</button></section><section class="card wide settings"><h2>Данные и отчёты</h2><div class="setting-row"><span><b>Резервная копия</b><br><small class="muted">Все профили и записи в JSON</small></span><button class="secondary" data-action="backup">Скачать</button></div><div class="setting-row"><span><b>Восстановление</b><br><small class="muted">Проверим файл перед заменой</small></span><button class="secondary" data-action="restore">Выбрать файл</button></div><div class="setting-row"><span><b>CSV и PDF</b><br><small class="muted">Отчёт по выбранному ребёнку</small></span><span><button class="secondary" data-action="csv">CSV</button> <button class="secondary" data-action="pdf">PDF</button></span></div><div class="setting-row"><span><b>Удалить все данные</b><br><small class="muted">Действие нельзя отменить</small></span><button class="danger" data-action="erase">Удалить</button></div><p class="disclaimer">Соня не использует аналитику и не отправляет фотографии или записи на сервер. Уведомления зависят от поддержки браузера и не гарантируются при полностью закрытом приложении.</p></section></div>`)}
function render(){document.documentElement.dataset.theme=state.settings.theme;const fn={today:todayView,history:historyView,stats:statsView,settings:settingsView}[view];$('#app').innerHTML=state.children.length?fn():welcome();bind();clearInterval(ticker);if(active())ticker=setInterval(()=>{if(view==='today')render()},30000)}
function welcome(){return `<section class="welcome"><div class="card welcome-card"><div class="welcome-ill">☾</div><div class="eyebrow">Бережно к вашему ритму</div><h1>Соня</h1><p class="muted">Спокойный трекер сна малыша. Без аккаунта, рекламы и передачи данных.</p><button class="primary" data-action="new-child">Создать профиль ребёнка</button><button class="secondary" data-action="demo">Посмотреть пример</button><p class="disclaimer">Все данные и фотографии сохраняются только в этом браузере.</p></div></section>`}

function modal(html){document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop"><div class="modal" role="dialog" aria-modal="true">${html}</div></div>`);$('.modal-backdrop').addEventListener('click',e=>{if(e.target===e.currentTarget)e.currentTarget.remove()});$('.modal [data-close]')?.addEventListener('click',()=>$('.modal-backdrop').remove())}
function childrenPicker(){modal(`<h2>Выберите ребёнка</h2><div class="entries">${state.children.map(c=>`<button class="entry" data-pick-child="${c.id}"><span class="entry-icon">${c.photo?`<img class="avatar" src="${c.photo}" alt="">`:'🧸'}</span><span class="entry-main"><strong>${esc(c.name)}</strong><span>${ageLabel(c)}${c.isDemo?' · демонстрационные данные':''}</span></span>${c.id===child().id?'<b>✓</b>':'<b>›</b>'}</button>`).join('')}</div><div class="actions"><button class="ghost" data-close>Закрыть</button><button class="primary" data-new-from-picker>+ Добавить</button></div>`);document.querySelectorAll('[data-pick-child]').forEach(b=>b.onclick=async()=>{state.settings.activeChild=b.dataset.pickChild;await save();$('.modal-backdrop').remove();render()});$('[data-new-from-picker]').onclick=()=>{$('.modal-backdrop').remove();childForm()}}
function childForm(c={}){modal(`<h2>${c.id?'Профиль ребёнка':'Новый профиль'}</h2><form id="child-form" class="form-grid"><input type="hidden" name="id" value="${c.id||''}"><div class="field full"><label>Имя *</label><input name="name" required maxlength="40" value="${esc(c.name||'')}"></div><div class="field"><label>Дата рождения *</label><input type="date" name="birthDate" required max="${dayKey(new Date())}" value="${c.birthDate||''}"></div><div class="field"><label>Пол</label><select name="sex"><option value="">Не указывать</option><option ${c.sex==='girl'?'selected':''} value="girl">Девочка</option><option ${c.sex==='boy'?'selected':''} value="boy">Мальчик</option></select></div><div class="field"><label>Ожидаемая дата рождения</label><input type="date" name="expectedDate" value="${c.expectedDate||''}"></div><div class="field"><label>Фотография (хранится локально)</label><input type="file" name="photo" accept="image/*"></div><div class="actions full">${c.id?'<button type="button" class="danger" data-delete-child>Удалить</button>':''}<button type="button" class="ghost" data-close>Отмена</button><button class="primary">Сохранить</button></div></form>`);$('#child-form').onsubmit=saveChild;if(c.id)$('[data-delete-child]').onclick=()=>deleteChild(c.id)}
async function fileData(file){if(!file)return null;if(file.size>3_000_000){toast('Выберите фото до 3 МБ');return null}return new Promise(r=>{const fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(file)})}
async function saveChild(e){e.preventDefault();const fd=new FormData(e.target),old=state.children.find(c=>c.id===fd.get('id')),photo=await fileData(fd.get('photo'));const c={...old,id:old?.id||uid(),name:fd.get('name').trim(),birthDate:fd.get('birthDate'),sex:fd.get('sex'),expectedDate:fd.get('expectedDate'),photo:photo||old?.photo||'',createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(old)state.children=state.children.map(x=>x.id===c.id?c:x);else state.children.push(c);state.settings.activeChild=c.id;await save();$('.modal-backdrop').remove();render();toast('Профиль сохранён')}
async function deleteChild(id){if(!confirm('Удалить профиль и все его записи? Это действие нельзя отменить.'))return;state.children=state.children.filter(c=>c.id!==id);state.events=state.events.filter(e=>e.childId!==id);state.settings.activeChild=state.children[0]?.id;await save();$('.modal-backdrop').remove();render()}
function sleepForm(e={}){const now=new Date(),start=e.start||new Date(now-60*60000).toISOString(),awakening=(e.awakenings||[])[0]||{};modal(`<h2>${e.id?'Запись сна':'Добавить сон'}</h2><form id="sleep-form" class="form-grid"><input type="hidden" name="id" value="${e.id||''}"><div class="field"><label>Начало *</label><input type="datetime-local" name="start" required value="${localInput(start)}"></div><div class="field"><label>Окончание *</label><input type="datetime-local" name="end" required value="${localInput(e.end||now)}"></div><div class="field"><label>Тип сна</label><select name="sleepType"><option value="day" ${e.sleepType==='day'?'selected':''}>Дневной</option><option value="night" ${e.sleepType==='night'?'selected':''}>Ночной</option></select></div><div class="field"><label>Качество</label><select name="quality"><option value="">Не указано</option>${['Спокойный','Обычный','Беспокойный'].map(x=>`<option ${e.quality===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Место</label><input name="location" placeholder="Кроватка, коляска…" value="${esc(e.location||'')}"></div><div class="field"><label>Как заснул</label><input name="method" placeholder="Самостоятельно, укачивание…" value="${esc(e.method||'')}"></div><div class="field full"><label>Ночное пробуждение (необязательно)</label><div class="form-grid"><input type="datetime-local" name="wakeStart" value="${awakening.start?localInput(awakening.start):''}"><input type="datetime-local" name="wakeEnd" value="${awakening.end?localInput(awakening.end):''}"><input name="wakeReason" placeholder="Причина" value="${esc(awakening.reason||'')}"><input name="settling" placeholder="Как снова заснул" value="${esc(awakening.settling||'')}"></div></div><div class="field full"><label>Заметка</label><textarea name="note" maxlength="1000">${esc(e.note||'')}</textarea></div><div class="actions full">${e.id?'<button type="button" class="danger" data-delete>Удалить</button>':''}<button type="button" class="ghost" data-close>Отмена</button><button class="primary">Сохранить</button></div></form>`);$('#sleep-form').onsubmit=saveSleep;if(e.id)$('[data-delete]').onclick=()=>deleteSleep(e.id)}
async function saveSleep(ev){ev.preventDefault();const f=new FormData(ev.target),start=new Date(f.get('start')),end=new Date(f.get('end'));if(end<=start){toast('Окончание должно быть позже начала');return}const id=f.get('id'),overlap=events().find(x=>x.id!==id&&new Date(x.start)<end&&new Date(x.end||Date.now())>start);if(overlap&&!confirm('Эта запись пересекается с другой. Всё равно сохранить?'))return;const wakes=[];if(f.get('wakeStart')&&f.get('wakeEnd')){const ws=new Date(f.get('wakeStart')),we=new Date(f.get('wakeEnd'));if(ws<start||we>end||we<=ws){toast('Проверьте время ночного пробуждения');return}wakes.push({id:uid(),start:ws.toISOString(),end:we.toISOString(),reason:f.get('wakeReason'),settling:f.get('settling')})}const old=state.events.find(x=>x.id===id),e={...old,id:id||uid(),childId:child().id,eventType:'sleep',start:start.toISOString(),end:end.toISOString(),sleepType:f.get('sleepType'),quality:f.get('quality'),location:f.get('location'),method:f.get('method'),note:f.get('note'),awakenings:wakes,source:old?.source||'manual',updatedAt:new Date().toISOString(),createdAt:old?.createdAt||new Date().toISOString()};state.events=id?state.events.map(x=>x.id===id?e:x):[...state.events,e];await save();$('.modal-backdrop').remove();render();toast('Запись сохранена')}
async function deleteSleep(id){if(!confirm('Удалить эту запись сна?'))return;state.events=state.events.filter(x=>x.id!==id);await save();$('.modal-backdrop').remove();render();toast('Запись удалена')}
async function toggle(){const a=active();if(a){a.end=new Date().toISOString();a.updatedAt=a.end;await save();vib();render();toast(`Сон завершён · ${durationLabel(sleepMinutes(a))}`);sleepForm(a)}else{const hour=new Date().getHours();state.events.push({id:uid(),childId:child().id,eventType:'sleep',sleepType:hour>=19||hour<7?'night':'day',start:new Date().toISOString(),end:null,awakenings:[],source:'timer',createdAt:new Date().toISOString()});await save();vib();render();toast('Таймер сна запущен')}}

async function demo(){const id=uid(),now=Date.now();state.children=[{id,name:'Мила · пример',birthDate:dayKey(new Date(now-8*2629800000)),sex:'girl',isDemo:true,createdAt:new Date().toISOString()}];state.settings.activeChild=id;state.demo=true;for(let d=0;d<7;d++){const base=startOfDay(new Date(now-d*86400000)).getTime();state.events.push({id:uid(),childId:id,eventType:'sleep',sleepType:'day',start:new Date(base+11*3600000).toISOString(),end:new Date(base+(12.4+(d%2)*.25)*3600000).toISOString(),awakenings:[],isDemo:true,source:'demo'},{id:uid(),childId:id,eventType:'sleep',sleepType:'night',start:new Date(base-3*3600000).toISOString(),end:new Date(base+6.5*3600000).toISOString(),awakenings:[],isDemo:true,source:'demo'})}await save();render();toast('Открыт демонстрационный профиль')}
function download(name,type,content){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function csv(){const rows=[['Ребёнок','Начало','Окончание','Тип','Минуты','Место','Качество','Заметка'],...events().map(e=>[child().name,e.start,e.end||'',e.sleepType,sleepMinutes(e),e.location||'',e.quality||'',e.note||''])];download(`sonya-${dayKey(new Date())}.csv`,'text/csv;charset=utf-8','\ufeff'+rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\n'))}
function backup(){download(`sonya-backup-${dayKey(new Date())}.json`,'application/json',JSON.stringify({schemaVersion:1,exportedAt:new Date().toISOString(),data:state},null,2))}
function restore(){const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=async()=>{try{const obj=JSON.parse(await i.files[0].text());if(obj.schemaVersion!==1||!Array.isArray(obj.data?.children)||!Array.isArray(obj.data?.events))throw Error();if(confirm(`Найдено профилей: ${obj.data.children.length}, записей: ${obj.data.events.length}. Заменить текущие данные?`)){state=obj.data;await save();render();toast('Данные восстановлены')}}catch{toast('Не удалось прочитать резервную копию')}};i.click()}
async function erase(){const word=prompt('Все профили и записи будут удалены. Введите УДАЛИТЬ для подтверждения:');if(word!=='УДАЛИТЬ')return;state=structuredClone(defaultState);await save();render();toast('Все данные удалены')}
async function notifications(){if(!('Notification'in window)){toast('Уведомления не поддерживаются');return}if(Notification.permission!=='granted'){const p=await Notification.requestPermission();if(p!=='granted'){toast('Разрешение не предоставлено');return}}state.settings.notifications=!state.settings.notifications;await save();render();toast(state.settings.notifications?'Напоминания включены':'Напоминания выключены')}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>sleepForm(state.events.find(e=>e.id===b.dataset.edit)));document.querySelectorAll('[data-edit-child]').forEach(b=>b.onclick=()=>childForm(state.children.find(c=>c.id===b.dataset.editChild)));document.querySelectorAll('[data-hmode]').forEach(b=>b.onclick=()=>{historyMode=b.dataset.hmode;render()});document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{period=b.dataset.period;render()});document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{selectedDate=new Date(b.dataset.day);historyMode='list';render()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{const a=b.dataset.action;if(a==='add')sleepForm();if(a==='toggle')toggle();if(a==='new-child')childForm();if(a==='children')childrenPicker();if(a==='demo')demo();if(a==='theme'){state.settings.theme=state.settings.theme==='dark'?'light':'dark';await save();render()}if(a==='vibration'){state.settings.vibration=!state.settings.vibration;await save();render()}if(a==='notifications')notifications();if(a==='backup')backup();if(a==='restore')restore();if(a==='csv')csv();if(a==='pdf')window.print();if(a==='erase')erase()})}

state=await load();render();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js'));
